services:
  entrance:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: entrance:latest
    container_name: entrance
    network_mode: "host"
    volumes:
      - ${ENTRANCE_CONFIG_FILE:-./config.yaml}:/app/config.yaml:ro
    environment:
      - ENTRANCE_CONFIG_FILE=/app/config.yaml
    restart: unless-stopped
