name: entrance
services:
  entrance:
    image: entrance:latest
    container_name: entrance
    ports:
      - "8000:8000"
    volumes:
      - ${ENTRANCE_CONFIG_FILE:-./config.yaml}:/app/config.yaml:ro
    environment:
      - ENTRANCE_CONFIG_FILE=/app/config.yaml
      - ENTRANCE_HOSTNAME=${ENTRANCE_HOSTNAME:-localhost}
    restart: unless-stopped
